apiVersion: v1
kind: Service
metadata:
  name: kid
  namespace: kube-system
  labels:
    run: kid
    dns: route53
  annotations:
     service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:xxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
     service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
     service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
     domainName: "kid.aws.camil.org"
spec:
  type: LoadBalancer
  ports:
  - port: 443
    targetPort: 5555
    protocol: TCP
  selector:
    run: kid

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kid
  namespace: kube-system
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        run: kid
    spec:
      containers:
      - name: kid
        image: dailyhotel/kid:0.1
        livenessProbe:
          tcpSocket:
            port: 5555
          timeoutSeconds: 120
        ports:
        - containerPort: 5555
        env:
          - name: CLIENT_ID
            value: "kid"
          - name: CLIENT_SECRET
            value: "OkUyDUnx8VN1IpS2szizfrKu"
          - name: ISSUER
            value: "https://dex.aws.camil.org"
          - name: LISTEN
            value: "http://0.0.0.0:5555"
          - name: REDIRECT_URI
            value: "https://kid.aws.camil.org/callback"
        imagePullPolicy: Always
